---
title: "R Notebook"
output: html_document
---



```{r, include = FALSE}
library(plyr)
library(stringr)
library(tidyverse)
options(width=1000)
power <- read_csv("~/Box Sync/Dissert Data/power/15.csv")
```

```{r, echo = FALSE, out.width="1920px",out.height="1080px", fig.width=20,fig.height=10,dpi=300}
ggplot(data = filter(power,
                     type == "toeplitz",
                     populations == 2,
                     !(ReductionMethod == "DataConcatScatterBlock"),
                     difference <= 1)) +
  geom_line(aes(x = difference, y = power, color = test)) +
  facet_grid(ReductionMethod ~ ReducedDimension)
```

```{r, echo = FALSE, out.width="1920px",out.height="1080px", fig.width=20,fig.height=10,dpi=300}
ggplot(data = filter(power,
                     type == "toeplitz",
                     populations == 3,
                     Samples == 15,
                     !(ReductionMethod == "DataConcatScatterBlock"),
                     difference <= 1)) +
  geom_line(aes(x = difference, y = power, color = test)) +
  facet_grid(ReductionMethod ~ ReducedDimension)
```
