---
title: "A Comparison of Tests Statistics for Equality of High-Dimensional Covariance Vectors"
subtitle: "A Monte Carlo Power Simulation Study"
author: "Ben Barnard"
output: revealjs::revealjs_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = FALSE)
```

## Overview of Topics

- Introduction of the problem

- Test Statistics

- SVD reduction

- Simulation study

- Summary

- Future work

- References

# Introduction

## Introduction

- Considering high-dimensional data

- Interested in comparing equality of 2 and k (3) covariance matrices

- ???? test statistics for testing equality of covariance matrices

- ???? dimension reduction methods via singular value decomposition

# Statistics for Testing Equality of Covariance Matrices

## Frobenius Norm

Most of the tests given are based off of the Frobenius Norm.

$$
\begin{align} 
d^2 &= \frac{tr(\Sigma_i - \Sigma_j)^2}{p} \\
&= \frac{tr(\Sigma_i^2)}{p} + \frac{tr(\Sigma_j^2)}{p} - \frac{2tr(\Sigma_i \Sigma_j)}{p}
\end{align}
$$

## Consistent Estimators

$$\hat{a}_{2i} = \frac{tr(V_i^2) - \frac{1}{n_i}tr(V_i)^2}{(n_i - 1)(n_i + 2)p} \xrightarrow{P} \frac{tr(\Sigma_i^2)}{p}$$
$$\hat{a}_2 = \frac{tr(V^2) - \frac{1}{n}tr(V)^2}{(n - 1)(n + 2)p} \xrightarrow{P} \frac{tr(\Sigma^2)}{p}$$

## Schott 2007

$$ T_{Sc} = \sum \limits^{k}_{i < j} \frac{(\hat{a}_{2i} + \hat{a}_{2j} - \frac{2}{p}tr(S_i S_j)) ^ 2}{\theta}$$
$$\theta = 4 \hat{a}_2^2 \left( \sum \limits_{i < j}^ k (\frac{1}{n_i} + \frac{1}{n_j}) + (k - 1)(k - 2) \sum \limits_{i = 1}^k n_i^{-2} \right)$$



## Srivastava 2007

$$T_{S7} = \sum \limits^k_{i=1} \frac{(\hat{a}_{2i} - \bar{\hat{a}}_2)^2}{\hat{\eta}_i^2}$$
$$\bar{\hat{a}}_2 = \frac{\sum \limits^k_{i = 1} \frac{\hat{a}_{2i}}{\hat{\eta}_i^2}}{\sum \limits^k_{i = 1} \hat{\eta}_i^{-2}}$$
$$\hat{\eta}_i^2 = \frac{4}{n^2_i}\hat{a}^2_2 \left( 1 + \frac{2 n_i \hat{a}_4}{p \hat{a}^2_2} \right)$$
$$\hat{a}_4 = \frac{p^{-1}tr(V^4) - p(4n^3+ 12n^2 + 18n)\hat{a}_1  - p^2(6n^2 4n)\hat{a}^2_1\hat{a}_2 - p(2n^3 + 5n^2 + 7n)\hat{a}^2_2 - p^3 n \hat{a}^4_1}{n^4 + 6n^3 + 21n^2 + 18n} \xrightarrow{P} \frac{tr(\Sigma^4)}{p}$$

$$\hat{a}_1 = \frac{tr(S)}{p}$$

    
## Srivastava and Yanagihara 2010

$$T_{SY} = \sum \limits^k_{i = 1} \frac{(\hat{\gamma}_i - \bar{\hat{\gamma}})^2}{\hat{\xi}^2_i}$$
$$\hat{\gamma}_i = \frac{\hat{a}_{2i}}{\hat{a}^2_{1i}}$$
$$\hat{\xi}^2_i = \frac{4}{n^2_i}\left( \frac{\hat{a}^2_2}{\hat{a}^4_1} + \frac{2 n_i}{p} \left( \frac{\hat{a}^3_2}{\hat{a}^4_1} - \frac{2\hat{a}_2\hat{a}_3}{\hat{a}_1^5} + \frac{\hat{a}_4}{\hat{a}_1^4}\right)\right)$$
$$\hat{a}_3 = \frac{p^{-1}tr(V^3) - p(3n^2 + 3n)\hat{a}_2\hat{a}_1 - p^2n\hat{a}^3_1}{n^3 +3n^2 + 4n}$$
$$\bar{\hat{\gamma}} = \frac{\sum \limits^k_{i = 1} \frac{\hat{\gamma}_{2i}}{\hat{\xi}_i^2}}{\sum \limits^k_{i = 1} \hat{\xi}_i^{-2}}$$

## Chaipitak and Chongcharoen 2013

$$T_{C} = \sum \limits^{k}_{i < j} \frac{(\hat{b} - 1)^2}{\hat{\delta}^2}$$

$$\hat{b} = \frac{max(\hat{a}_{2i}, \hat{a}_{2j})}{min(\hat{a}_{2i}, \hat{a}_{2j})}$$
$$\hat{\delta}^2 = 4 \left( \frac{2\hat{a}_4}{p \hat{a}_2^2} \sum \limits^2_{i=1} \frac{1}{n_i -1} + \sum \limits^2_{i=1} \frac{1}{(n_i - 1)^2} \right)$$

## Srivastava et al. 2014

$$ T_{S14} = \sum \limits^{k}_{i < j} \frac{(\hat{a}_{2i} + \hat{a}_{2j} - \frac{2}{p}tr(S_i S_j)) ^ 2}{\theta}$$
$$\hat{a}_{2i} = \frac{1}{pn_i(n_i -1)(n_i -2)(n_i -3)}\left( (n_i -2)(n_i -1)tr(V_i^2) - n(n - k)tr(D^2_i) + tr(V_i)^2 \right)$$
$$\hat{a}_2 = \frac{\sum \limits^k_{i=1} n_i \hat{a}_{2i}}{\sum \limits^k_{i=1} n_i}$$

## Ishii et al. 2016

$$T_I = \prod \limits^{k}_{i < j} \tilde{\lambda}_* \tilde{h}_* \tilde{\gamma}_*$$
$$\tilde{\lambda}_* = \frac{max(\tilde{\lambda}_i, \tilde{\lambda}_j)}{min(\tilde{\lambda}_i, \tilde{\lambda}_j)}$$
$$\tilde{\lambda}_i = \hat{\lambda}_i - \frac{tr(S_D) - \sum \limits^i_{j = 1}\hat{\lambda}_j}{n - 1-i}$$

$$\tilde{h}_* = max(|\tilde{h}^T_i \tilde{h}_j|, |\tilde{h}^T_i \tilde{h}_j|^{-1})$$
$$\tilde{h}_i = ((n-1)\tilde{\lambda}_i)^{-1/2}(\boldsymbol{X} - \boldsymbol{\overline{X}})\hat{\boldsymbol{\mu}}_i$$
$$\tilde{\gamma}_* = max()$$
  
# Dimension Reduction via the Singular Value Decomposition

## Dimension Reduction using the Singular Value Decomposition 
- For samples $\boldsymbol{X}_1$ and $\boldsymbol{X}_2$, let 
  $\boldsymbol{X} = \left[ \boldsymbol{X}_1 \vdots \, \boldsymbol{X}_2 \right]^T$.

- Let $\boldsymbol{S}_t$ represent the scatter matrix of $\boldsymbol{X}$, with rank $t$.

- Let $\boldsymbol{S}_t = \boldsymbol{UDU}^T$ represent the singular value decompostion of $\boldsymbol{S}_t$.

    - $\boldsymbol{U}$ is orthogonal.

    - $\boldsymbol{D} = \begin{bmatrix} \boldsymbol{D}_t & \boldsymbol{O} \\ \boldsymbol{O} & \boldsymbol{O} \end{bmatrix}$.
  
<div class="notes">
Scatter matrix: $X^t C X$ where $C = I - (1/n) 1_{n \times n}$
</div>

## Dimension Reduction Continued

- Partition $\boldsymbol{U}$ such that $\boldsymbol{U} = \left[ \boldsymbol{U}_1 \vdots \, \boldsymbol{U}_2 
  \right]$ with $\boldsymbol{U}_1 \in \mathbb{R}^{p \times t}$.

- Project $\boldsymbol{X}_1$ and $\boldsymbol{X}_2$ to $t$ dimensions by taking $\boldsymbol{X}_{Ri}^T = \boldsymbol{U}_1^T 
  \boldsymbol{X}_i^T$.

# Simulation Study

## Parameters for Simulation Study

The data sets generated for the simulation study have the following characteristics:

- $n_i = 15$

- $p = 100$

- Generating data sets from $\mathcal{N}_p \left( \boldsymbol{0}, \boldsymbol{\Sigma} \right)$

- Number of repetitions is 1000

## Description of $\boldsymbol{\Sigma}$

- Selected $\boldsymbol{\Sigma}_{0.5}$

    - $\boldsymbol{\Sigma}_{a}$ represents a covariance matrix with unit variances, where 
      $\text{Cov}\left(X_{i}, X_{j} \right) = a$.
      
- For example, if $p = 6$, then
  \[
  \boldsymbol{\Sigma}_{a} = \begin{bmatrix}
  1 & a & a^2 & a^3 & a^4 & a^5 \\
  a & 1 & a & a^2 & a^3 & a^4 \\
  a^2 & a & 1 & a & a^2 & a^3 \\
  a^3 & a^2 & a & 1 & a & a^2 \\
  a^4 & a^3 & a^2 & a & 1 & a \\
  a^5 & a^4 & a^3 & a^2 & a & 1
  \end{bmatrix}.
  \]

## Simulation Results for m = 1

## Simulation Results for m = 5

## Simulation Results for m = 10

# Summary and References

## Summary


## Future Work


## References {.smaller}

---
nocite: |
  @srivastava_multivariate_2007, @srivastava_test_2008, @ye_regularized_2006, 
  @bai_effect_1996, @thulin_high-dimensional_2014
...

