// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// Ahmad2017Stat
double Ahmad2017Stat(List x);
RcppExport SEXP _covTestR_Ahmad2017Stat(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(Ahmad2017Stat(x));
    return rcpp_result_gen;
END_RCPP
}
// c3
double c3(arma::mat x);
RcppExport SEXP _covTestR_c3(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(c3(x));
    return rcpp_result_gen;
END_RCPP
}
// c2
double c2(arma::mat x);
RcppExport SEXP _covTestR_c2(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(c2(x));
    return rcpp_result_gen;
END_RCPP
}
// c1
double c1(arma::mat x);
RcppExport SEXP _covTestR_c1(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(c1(x));
    return rcpp_result_gen;
END_RCPP
}
// bilinearquad
double bilinearquad(arma::mat x);
RcppExport SEXP _covTestR_bilinearquad(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(bilinearquad(x));
    return rcpp_result_gen;
END_RCPP
}
// bilinearsquare
double bilinearsquare(arma::mat x);
RcppExport SEXP _covTestR_bilinearsquare(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(bilinearsquare(x));
    return rcpp_result_gen;
END_RCPP
}
// bilinearcube
double bilinearcube(arma::mat x);
RcppExport SEXP _covTestR_bilinearcube(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(bilinearcube(x));
    return rcpp_result_gen;
END_RCPP
}
// bilinearoff
double bilinearoff(arma::mat x);
RcppExport SEXP _covTestR_bilinearoff(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(bilinearoff(x));
    return rcpp_result_gen;
END_RCPP
}
// quadra
double quadra(arma::mat x);
RcppExport SEXP _covTestR_quadra(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(quadra(x));
    return rcpp_result_gen;
END_RCPP
}
// BoxesMStat
double BoxesMStat(List x);
RcppExport SEXP _covTestR_BoxesMStat(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(BoxesMStat(x));
    return rcpp_result_gen;
END_RCPP
}
// Chaipitak2013poolStat
double Chaipitak2013poolStat(List x);
RcppExport SEXP _covTestR_Chaipitak2013poolStat(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(Chaipitak2013poolStat(x));
    return rcpp_result_gen;
END_RCPP
}
// Chaipitak2013Stat
double Chaipitak2013Stat(List x);
RcppExport SEXP _covTestR_Chaipitak2013Stat(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(Chaipitak2013Stat(x));
    return rcpp_result_gen;
END_RCPP
}
// Ishii2016Stat
double Ishii2016Stat(List x);
RcppExport SEXP _covTestR_Ishii2016Stat(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(Ishii2016Stat(x));
    return rcpp_result_gen;
END_RCPP
}
// Schott2001Stat
double Schott2001Stat(List x);
RcppExport SEXP _covTestR_Schott2001Stat(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(Schott2001Stat(x));
    return rcpp_result_gen;
END_RCPP
}
// Schott2007Stat
double Schott2007Stat(List x);
RcppExport SEXP _covTestR_Schott2007Stat(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(Schott2007Stat(x));
    return rcpp_result_gen;
END_RCPP
}
// Schott2007pooledStat
double Schott2007pooledStat(List x);
RcppExport SEXP _covTestR_Schott2007pooledStat(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(Schott2007pooledStat(x));
    return rcpp_result_gen;
END_RCPP
}
// Srivastava2007Stat
double Srivastava2007Stat(List x);
RcppExport SEXP _covTestR_Srivastava2007Stat(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(Srivastava2007Stat(x));
    return rcpp_result_gen;
END_RCPP
}
// Srivastava2014Stat
double Srivastava2014Stat(List x);
RcppExport SEXP _covTestR_Srivastava2014Stat(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(Srivastava2014Stat(x));
    return rcpp_result_gen;
END_RCPP
}
// Srivastava2014poolStat
double Srivastava2014poolStat(List x);
RcppExport SEXP _covTestR_Srivastava2014poolStat(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(Srivastava2014poolStat(x));
    return rcpp_result_gen;
END_RCPP
}
// SrivastavaYanagihara2010Stat
double SrivastavaYanagihara2010Stat(List x);
RcppExport SEXP _covTestR_SrivastavaYanagihara2010Stat(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(SrivastavaYanagihara2010Stat(x));
    return rcpp_result_gen;
END_RCPP
}
