# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Ahmad2017Stat <- function(x) {
    .Call('covTest_Ahmad2017Stat', PACKAGE = 'covTest', x)
}

BoxesMStat <- function(x) {
    .Call('covTest_BoxesMStat', PACKAGE = 'covTest', x)
}

Chaipitak2013poolStat <- function(x) {
    .Call('covTest_Chaipitak2013poolStat', PACKAGE = 'covTest', x)
}

Chaipitak2013Stat <- function(x) {
    .Call('covTest_Chaipitak2013Stat', PACKAGE = 'covTest', x)
}

Ishii2016Stat <- function(x) {
    .Call('covTest_Ishii2016Stat', PACKAGE = 'covTest', x)
}

Schott2001Stat <- function(x) {
    .Call('covTest_Schott2001Stat', PACKAGE = 'covTest', x)
}

Schott2007Stat <- function(x) {
    .Call('covTest_Schott2007Stat', PACKAGE = 'covTest', x)
}

Schott2007pooledStat <- function(x) {
    .Call('covTest_Schott2007pooledStat', PACKAGE = 'covTest', x)
}

Srivastava2007Stat <- function(x) {
    .Call('covTest_Srivastava2007Stat', PACKAGE = 'covTest', x)
}

Srivastava2014Stat <- function(x) {
    .Call('covTest_Srivastava2014Stat', PACKAGE = 'covTest', x)
}

Srivastava2014poolStat <- function(x) {
    .Call('covTest_Srivastava2014poolStat', PACKAGE = 'covTest', x)
}

SrivastavaYanagihara2010Stat <- function(x) {
    .Call('covTest_SrivastavaYanagihara2010Stat', PACKAGE = 'covTest', x)
}

c3 <- function(x) {
    .Call('covTest_c3', PACKAGE = 'covTest', x)
}

c2 <- function(x) {
    .Call('covTest_c2', PACKAGE = 'covTest', x)
}

c1 <- function(x) {
    .Call('covTest_c1', PACKAGE = 'covTest', x)
}

bilinearquad <- function(x) {
    .Call('covTest_bilinearquad', PACKAGE = 'covTest', x)
}

bilinearsquare <- function(x) {
    .Call('covTest_bilinearsquare', PACKAGE = 'covTest', x)
}

bilinearcube <- function(x) {
    .Call('covTest_bilinearcube', PACKAGE = 'covTest', x)
}

bilinearoff <- function(x) {
    .Call('covTest_bilinearoff', PACKAGE = 'covTest', x)
}

quadra <- function(x) {
    .Call('covTest_quadra', PACKAGE = 'covTest', x)
}

