# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Ahmad2017Stat <- function(x) {
    .Call('EqualCov_Ahmad2017Stat', PACKAGE = 'EqualCov', x)
}

c3 <- function(x) {
    .Call('EqualCov_c3', PACKAGE = 'EqualCov', x)
}

c2 <- function(x) {
    .Call('EqualCov_c2', PACKAGE = 'EqualCov', x)
}

c1 <- function(x) {
    .Call('EqualCov_c1', PACKAGE = 'EqualCov', x)
}

bilinearquad <- function(x) {
    .Call('EqualCov_bilinearquad', PACKAGE = 'EqualCov', x)
}

bilinearsquare <- function(x) {
    .Call('EqualCov_bilinearsquare', PACKAGE = 'EqualCov', x)
}

bilinearcube <- function(x) {
    .Call('EqualCov_bilinearcube', PACKAGE = 'EqualCov', x)
}

bilinearoff <- function(x) {
    .Call('EqualCov_bilinearoff', PACKAGE = 'EqualCov', x)
}

quadra <- function(x) {
    .Call('EqualCov_quadra', PACKAGE = 'EqualCov', x)
}

BoxesMStat <- function(x) {
    .Call('EqualCov_BoxesMStat', PACKAGE = 'EqualCov', x)
}

Chaipitak2013poolStat <- function(x) {
    .Call('EqualCov_Chaipitak2013poolStat', PACKAGE = 'EqualCov', x)
}

Chaipitak2013Stat <- function(x) {
    .Call('EqualCov_Chaipitak2013Stat', PACKAGE = 'EqualCov', x)
}

Ishii2016Stat <- function(x) {
    .Call('EqualCov_Ishii2016Stat', PACKAGE = 'EqualCov', x)
}

Schott2001Stat <- function(x) {
    .Call('EqualCov_Schott2001Stat', PACKAGE = 'EqualCov', x)
}

Schott2007Stat <- function(x) {
    .Call('EqualCov_Schott2007Stat', PACKAGE = 'EqualCov', x)
}

Schott2007pooledStat <- function(x) {
    .Call('EqualCov_Schott2007pooledStat', PACKAGE = 'EqualCov', x)
}

Srivastava2007Stat <- function(x) {
    .Call('EqualCov_Srivastava2007Stat', PACKAGE = 'EqualCov', x)
}

Srivastava2014Stat <- function(x) {
    .Call('EqualCov_Srivastava2014Stat', PACKAGE = 'EqualCov', x)
}

Srivastava2014poolStat <- function(x) {
    .Call('EqualCov_Srivastava2014poolStat', PACKAGE = 'EqualCov', x)
}

SrivastavaYanagihara2010Stat <- function(x) {
    .Call('EqualCov_SrivastavaYanagihara2010Stat', PACKAGE = 'EqualCov', x)
}

